# Site settings
title: Another Coder Blog
email: mpanunzio@hiddenhost.org
description: d33pcode's survival diary to life and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://d33pcode.github.io" # the base hostname & protocol for your site
twitter_username: d33pcode
github_username:  d33pcode

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
kramdown:
    input: GFM  # Github Flavored Markdown
