# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Another Coder Blog
email: mpanunzio@hiddenhost.org
description: > # this means to ignore newlines until "baseurl:"
    d33pcode's survival diary to life and technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://d33pcode.github.io" # the base hostname & protocol for your site
twitter_username: d33pcode
github_username:  d33pcode

# Build settings
markdown: kramdown
kramdown:
    input: GFM  # Github Flavored Markdown
